Student Management System/django_site/django_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('student_management/', include('student_management.urls')),
    path('admin/', admin.site.urls),
]

Student Management System/django_site/student_management/urls.py
from django.urls import path, include
from . import views

app_name = 'student_management'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/course/', views.CourseCreateView.as_view(), name='register_course'),
    path('<int:pk>/course/', views.CourseView.as_view(), name='course'),
    path('<int:pk>/profile/', views.ProfileView.as_view(), name='profile'),
    path('my/courses/', views.StudentCourses.as_view(), name='student_courses'),
    path('accounts/', include('django.contrib.auth.urls'),),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('register/', views.signup, name='register'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.logout, name='log_out'),
]


Student Management System/django_site/student_management/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, User
from django.urls import reverse


class Teacher(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=45)
    title = models.CharField(max_length=45)
    bio = models.CharField(max_length=400)

    def __str__(self):
        return str(self.id) + ": " + str(self.name)


class Subject(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=255)

    def __str__(self):
        return str(self.id) + ": " + str(self.name)


class Course(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=45)
    description = models.TextField(max_length=400)
    level = models.CharField(max_length=25)
    publication_date = models.DateField(auto_now=True)
    start_date = models.DateTimeField()
    price = models.FloatField()
    occupancy = models.IntegerField(default=0)
    occupancy_limit = models.IntegerField(default=50)

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return str(self.id) + ": " + str(self.name)

    def get_absolute_url(self):
        return reverse('student_management:course', kwargs={'pk': self.id})


class Student(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    grade = models.IntegerField()

    courses = models.ManyToManyField(Course)

    def __str__(self):
        return str(self.name) + " " + str(self.last_name)









Student Management System/django_site/student_management/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Course


class LogInForm(AuthenticationForm):
    username = forms.CharField(max_length=25)
    # password = forms.CharField(max_length=25)

    class Meta:
        model = User
        fields = ['username', 'password']

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=25)
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=45)
    grade = forms.IntegerField()

    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name',  'email', 'password1', 'password2',
        ]

    # def save(self, commit=True):
    #     user = super(RegisterForm, self).save(commit=False)
    #     user.email = self.cleaned_data["email"]
    #     if commit:
    #         user.save()
    #     return user


class ProfileForm(forms.ModelForm):

    # def __init__(self):
    #     super(ProfileForm, self).__init__()
    #     return

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            ]


class CreateCourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = [
            'id',
            'name',
            'subject',
            'description',
            'level',
            # 'publication_date',
            'start_date',
            'price',
            'occupancy_limit',
            'teacher',
        ]

Student Management System/django_site/student_management/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
# from django.views.generic import CreateView

from .models import Course, Student
from django.utils import timezone
from django.contrib.auth.models import User
from .forms import RegisterForm, ProfileForm, LogInForm, CreateCourseForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth

import pdb


class IndexView(generic.ListView):
    template_name = 'student_management/index.html'
    context_object_name = 'courses_list'

    def get_queryset(self):
        return Course.objects.all().order_by('start_date')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['students'] = Student.objects.all()
        context['now'] = timezone.now()

        if self.request.user.is_authenticated:
            student = Student.objects.get(user=self.request.user.id)
            if student is not None:
                context['student_id'] = student.id
                context['user_id'] = self.request.user.id

                # if self.request.user.is_authenticated:
        #     context['user_name'] = self.request.user.username
        #     context['user_id'] = self.request.user.id
        # else:
        #     context['user_name1'] = "WHY WHY WHYYYYY"
        return context


class CourseView(generic.DetailView):

    template_name = 'student_management/course_details.html'
    context_object_name = 'course'
    model = Course

    def get_queryset(self):
        return Course.objects

    def get_context_data(self, **kwargs):
        context = super(CourseView, self).get_context_data(**kwargs)
        context['loggedIn'] = False
        context['student_has_course'] = False
        if self.request.user.is_authenticated:
            context['user'] = self.request.user.username
            context['loggedIn'] = True
            # student = Student.objects.get(user=self.request.user.id)
            #
            # course = student.courses.through.objects.get(course_id=kwargs.get('pk'), student_id=student.id)
            # if course is not None:
            #     context['student_has_course'] = True
        else:
            context['user'] = "not logged in"
        print("context", context)
        return context

    # def get(self, request, pk):
    #     if self.request.user.is_authenticated:
    #         student = Student.objects.get(user=self.request.user.id)
    #         print("course_id", pk)
    #         print("student_id", student.id)
    #         course = student.courses.through.objects.get(course_id=pk, student_id=student.id)
    #         if course is not None:
    #             context['student_has_course'] = True
    #             self.extra_context()

    def post(self, request, pk):
        # return self.subscribe_un_to_course(request, pk, subscribe=True)
        if self.request.user.is_authenticated:
            student = Student.objects.get(user=self.request.user.id)
            course = Course.objects.get(id=pk)
            # student = get_object_or_404(Student, id=self.request.user.id)
            if course.occupancy < course.occupancy_limit:
                student.courses.add(course.id)
                student.save()
                course.occupancy += 1
                course.save()
            else:
                return show_base_error_message(request, title="Register error", message="This course is full")

            # pdb.set_trace()
            return HttpResponseRedirect(reverse_lazy('student_management:student_courses'))
        else:
            return HttpResponseRedirect(reverse_lazy('student_management:login'))

    # def delete(self, request, pk):
    #     self.subscribe_un_to_course(request, pk, subscribe=False)

    # def subscribe_un_to_course(self, request, course_id, subscribe):
    #     if self.request.user.is_authenticated:
    #         student = Student.objects.get(user=self.request.user.id)
    #         course = Course.objects.get(id=pk)
    #         # student = get_object_or_404(Student, id=self.request.user.id)
    #
    #         if subscribe:
    #             # student1 = get_object_or_404(Student, =title)
    #             student.courses.add(course.id)
    #             student.save()
    #         else:
    #             student_course = student.courses.through.objects.filter(student_id=student.id, course_id=course.id)
    #             student_course.delete()
    #
    #         # pdb.set_trace()
    #         return HttpResponseRedirect(reverse_lazy('student_management:student_courses'))
    #     else:
    #         return HttpResponseRedirect(reverse_lazy('student_management:login'))


class LogInView(generic.FormView):
    template_name = 'student_management/users/login.html'
    form_class = LogInForm
    user_id = 0
    success_url = reverse_lazy('student_management:index')

    def get_success_url(self):
        # return reverse_lazy('student_management:profile', args=(self.user_id,))
        return reverse_lazy('student_management:index')

    def get(self, request):
        if request.user.is_authenticated:
            return show_base_error_message(request, title="login error", message="You are already logged in")

        # return render(request, template_name=self.template_name)      #correct but missing super functionality
        return super().get(request)

    def post(self, request):

        if request.user.is_authenticated and request.POST.get('username') == request.user.username:
        # if request.user.is_authenticated:
            return show_base_error_message(request, title="login error", message="You are already logged in")

        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('student_management:profile', args=(user.id,)))
        else:
            return show_base_error_message(self.request, title="login error", message="invalid username or password")


def log_out(request):
    if request.user.is_authenticated:
        logout(request)
        #TODO: ADD success message
    return HttpResponseRedirect(reverse_lazy('student_management:index'))


class RegisterView(generic.CreateView):
    template_name = 'student_management/users/register.html'
    form_class = RegisterForm
    # user_id = User.objects.get(username=User.username).pk
    # success_url = reverse_lazy('student_management:profile', args=(user_id,))
    success_url = reverse_lazy('student_management:index')
    # model = User

    def form_valid(self, form):
        if self.request.user.is_authenticated:   #TODO: add message that is alreadi logedin'
            return HttpResponseRedirect(reverse_lazy('student_management:index'))
            # return HttpResponseRedirect(reverse_lazy('student_management:profile', kwargs={'pk': self.pk}))

        # form = RegisterForm(request.POST)
        # if form.is_valid():
        #     form.save()
        super().form_valid(form)
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1']) #request.POST['username'], password=request.POST['password1'])
        login(self.request, user)
        student = Student()
        student.name = form.cleaned_data.get('first_name')
        student.last_name = form.cleaned_data.get('last_name')
        student.email = form.cleaned_data.get('email')
        student.grade = form.cleaned_data.get('grade')
        student.user = user
        student.save()
        return HttpResponseRedirect(reverse_lazy('student_management:profile', kwargs={'pk': user.id}))
        # else:
        #     #TODO: show error message
        #     return super().form_valid(form)


class ProfileView(generic.UpdateView):
    model = User
    form_class = ProfileForm
    success_url = reverse_lazy('student_management:index')
    template_name = 'student_management/users/profile.html'


class StudentCourses(generic.ListView):
    model = Course
    template_name = 'student_management/student_curses.html'
    context_object_name = 'courses_list'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        student = Student.objects.get(user=self.request.user.id)
        student_courses = student.courses.through.objects.filter(student_id=student.id)
        # student_courses = student.courses.through.objects.filter(student_id=student.id, course_id=course.id)
        courses_list = []
        for sc in student_courses:
            courses_list.append(Course.objects.get(id=sc.course_id))

        data['courses_list'] = courses_list

        data['student'] = Student.objects.get(user=self.request.user.id)
        return data

    def get(self, request):
        if not request.user.is_authenticated:
            return show_base_error_message(request, title="Error", message="You are not logged in")

        return super().get(request)

    def post(self, request):   # TODO: try delete metod (not used because csrf error)
        course_id = request.POST.get('course_id')
        student = Student.objects.get(user=self.request.user.id)    # TODO: Try to get form context
        student_course = student.courses.through.objects.filter(student_id=student.id, course_id=course_id)
        course = Course.objects.get(id=course_id)
        course.occupancy -= 1
        course.save()
        print(student_course)
        student_course.delete()


Student Management System/django_site/student_management/templates/student_management/base.html
<!DOCTYPE HTML PUBLIC "">
{% load static %}
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'student_management/index.css' %}">
        <title>Student Management System</title>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
        {% block head %}


        {% endblock %}
    </head>
    <body>

        <div id="container">
                {% block header %}
                    <div id="header">
                        <h1>Student Management System</h1>
                        <ul>
                            <li><a href="/student_management/login">Loging</a></li>
                            <li><a href="{% url 'student_management:logout' %}">Logout</a></li>
                            <li><a href="{% url 'student_management:register' %}">Register</a></li>
                        </ul>
                        {% if loggedIn %}
                        <a>logged as: </a>
                        {% endif %}
                        <a>{{ user }}</a>
                    </div>
                {% endblock %}

                <div id="wrapper">

                    <div id="content">
                    {% block content %}

                        {% if title %}
                        <h1 id="title" >{{ title }}</h1>
                        {% endif %}
                        {% if message %}
                        <a id="message">{{ message }}</a>
                        {% endif %}
                    {% endblock %}
                    </div>
                </div>
                <div id="navigation">
                    <p><strong>Navigation Menu</strong></p>
                    <h3>Usefull links</h3>
<!--                    {% if mainLinks %}-->
<!--                    <ul>-->
<!--&lt;!&ndash;                        {% for link in links %}&ndash;&gt;-->
<!--&lt;!&ndash;                            <li><a href="{% url link.path %}">{{link.name}}</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                        {% endfor %}&ndash;&gt;-->
<!--                        <li><a href="{% url 'student_management:index' %}">Home</a> </li>-->
<!--                    </ul>-->
<!--                    {% else %}-->
<!--                        <p>No links available</p>-->
<!--                    {% endif %}-->

                    <nav>
<!--                        <a>TO DO: add links</a>-->
                        <a href="{% url 'student_management:index' %}">Home</a>
                        <a href="{% url 'student_management:student_courses' %}">My courses</a>
                        {% if user_id %}
                        <a href="{% url 'student_management:profile' pk=user_id %}">My profile</a>
                        {% endif %}
                        <a href="{% url 'student_management:register_course' %}">Register Course</a>
                        <a href="#">Contact</a>
                    </nav>
                </div>

                <div id="extra">
                    <p><strong> Additional PLACE HOLDER</strong></p>
                    <h3>In this guide you will learn:</h3>
                    <ul>
                        <li>How to use CSS Flexbox to build modern layouts</li>
                        <li>How to align items both vertically and horizontally</li>
                        <li>How to order items within container</li>
                        <li>And more</li>
                    </ul>
                </div>

                <div id="footer">
                    <ul>
                        <li><a href="/student_management/login">Loging</a></li>
                        <li><a href="{% url 'student_management:logout' %}">logout</a></li>
                        <li><a href="{% url 'student_management:register' %}">register</a></li>
                    </ul>
                </div>
        </div>

    </body>
</html>

Student Management System/django_site/student_management/templates/student_management/course_details.html
{% extends "student_management/base.html" %}


{% block content %}
    <h2><strong>{{course.name}}</strong></h2>
    <p><strong>Description:</strong></p> <p>{{course.description}}</p>
    <p><strong>level: </strong></p><p>{{course.level}}</p>
    <p><strong>start date: </strong></p><p>{{course.start_date}}</p>
    <p><strong>price: </strong></p><p>{{course.price}}</p>

    {% if student_has_course %}

    {% else %}
    <form action="." method="POST">
        {% csrf_token %}
        <input type="hidden" name="subscribe_to_course" value="True">
        <button type="submit">Register</button>
    </form>
    {% endif %}

{% endblock %}

Student Management System/django_site/student_management/templates/student_management/course_form.html
{% extends "student_management/base.html" %}


{% block content %}
    <h2>Create course</h2>
    <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>

{% endblock %}

Student Management System/django_site/student_management/templates/student_management/index.html
{% extends "student_management/base.html" %}


{% block content %}

            <h2><strong>Available courses</strong></h2>
<!--            <h3>Available courses </h3>-->
            {% if courses_list %}
                <ul id="index_courses_list">
                {% for course in courses_list %}
                    <li><a href="/student_management/{{course.id}}/course">{{course.name}}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>There are not courses available.</p>
            {% endif %}

{% endblock %}

Student Management System/django_site/student_management/templates/student_management/student_curses.html
{% extends "student_management/base.html" %}


{% block content %}
    <strong><h1>{{student.name}}</h1></strong>
    <a>Subscribed courses</a>
    {% if courses_list %}
    <ul>
        {% for course in courses_list %}
        <li>
            <p><strong>{{course.name}}</strong></p>
            <p>{{course.description}}</p>
<!--            <p>level: </p><p>{{course.level}}</p>-->
            <p>start date: </p><p>{{course.start_date}}</p>
<!--            <p>price: </p><p>{{course.price}}</p>-->
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="course_id" value="{{course.id}}">
                <button type="submit">Un register</button>
            </form>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>You are not subscribed to any courses yet.</p>
        <a class="my_links" href="{% url 'student_management:index' %}">Go find a course for you</a>
    {% endif %}

{% endblock %}